# Generated by Django 4.2 on 2023-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0002_category_alter_dish_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['id', 'username'], name='food_order__id_f7a637_idx'),
        ),
    ]
