# Generated by Django 4.2 on 2023-05-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0003_employee_food_order__id_f7a637_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='food_order__id_f7a637_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
